# Generated by Django 4.2.1 on 2023-06-04 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_personaldetails_delete_narayan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personaldetails',
            old_name='fname',
            new_name='fullName',
        ),
        migrations.RemoveField(
            model_name='personaldetails',
            name='lname',
        ),
    ]
