# Generated by Django 4.2.1 on 2023-06-04 16:14

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_rename_fname_personaldetails_fullname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True),
        ),
    ]
