# Generated by Django 4.2.1 on 2023-06-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_alter_personaldetails_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personaldetails',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
